FROM base-image

ARG PROJECT_NAME="app"
ARG DEBUG=false
ARG DISTRO
ARG APT_CACHER_SERVER
ARG EXPOSED_PORTS

ENV PROJECT_USER=$PROJECT_NAME \
	PROJECT_GROUP=$PROJECT_NAME \
	PROJECT_PASSWORD=$PROJECT_NAME \
	PROJECT_NAME=$PROJECT_NAME \
	PROJECT_DIR="/srv/$PROJECT_NAME" \
	DEBUG=$DEBUG \
	APT_CACHER_SERVER=$APT_CACHER_SERVER

RUN mkdir -p $PROJECT_DIR

ADD ./dists/$DISTRO/assets /tmp/$PROJECT_NAME/
RUN chmod 755 /tmp/$PROJECT_NAME/install.sh && /tmp/$PROJECT_NAME/install.sh

WORKDIR $PROJECT_DIR

EXPOSE 80 443 $EXPOSED_PORTS

ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf", "--nodaemon"]